services:
  - type: web
    name: offsydeb-api
    runtime: node
    buildCommand: npm install -g bun && bun install && npx playwright install chromium --with-deps
    startCommand: bun start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: false
